name: Publish
on:
  push:
    branches:
      - main
    tags:
      - '!*'
  # pull_request_target:
  #   types:
  #     - closed
  #   branches:
  #     - 'next'

jobs:
  localization:
    uses: ./.github/workflows/crowdin.yml
    if: ${{ github.ref == 'refs/heads/next' }}
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }} 
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }} 
      PAT: ${{ secrets.PAT }} 

  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs:
      - localization
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - run: git pull

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 

      - name: Build, Version & Publish packages
        run: yarn run publish
        env:
          REF: ${{ github.ref }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          GH_TOKEN: ${{ github.token }}
